services:
  jenkins:
    container_name: jenkins
    build:
      context: ./
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
    # folder to save the configuration of jenkins
      - "../../../JenkinsCurrentConfiguration:/var/jenkins_home"
    # share the pre-configured ssh private key + public key to share with the other services
      - "/c/Users/almog/Desktop/PrivateFiles/JenkinsSSH:/root/.ssh/"
    restart: always
    user:
      root
    networks:
      - global-docker-container-network
    tty: true
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
networks:
  global-docker-container-network:
    external: true

# to start docker:
# apt-get install -y docker-ce containerd.io docker-buildx-plugin docker-compose-plugin 
# service docker start

