services:
  jenkins:
    container_name: jenkins
    build:
      context: ./
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
    # shared folder with my pc
      - "../../../JenkinsCurrentConfiguration:/var/jenkins_home"
    # folder to save the configuration of jenkins
      - "../JenkinsSharedVolume:/var/jenkins_home/SharedFiles"
    restart: always
    user:
      root
    networks:
      - global-docker-container-network
    tty: true
    privileged: true
networks:
  global-docker-container-network:
    external: true


