services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.426.2-jdk17
    build:
      context: Installation
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/tmp/jenkins-data:/var/jenkins_home"
      - "./JenkinsSharedVolume:/var/jenkins_home/SharedFiles"
    deploy:
      restart_policy:
        condition: on-failure
    user:
      root
  remote-host-ssh:
    container_name: remote-host-ssh
    image: centos
    build:
      context: RemoteHostSSH
    deploy:
      restart_policy:
        condition: on-failure
networks:
  jenkins-net:
    external: true

