pipeline {
    agent any
    stages {
        stage('Create External AWS Infrastructure - Terraform') {
            steps {
                echo 'Create/Comply the exteranl infrastructre in AWS Terraform'
                sh 'ssh-keygen -f "/root/.ssh/known_hosts" -R "terraform-aws"'
                sh 'ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa jenkins-remote-user@terraform-aws "cd /Terraform/TerraformAWSInfrastructure/TerraformApp && ./terraform_deploy.sh" > /root/terraform_script_logs'
                echo "Terraform infrastructure was successfully deployed on AWS"
                // save the public ip of the ec2 for later use
                sh 'tail -1 /root/terraform_script_logs > ec2_public_ip'
            }
        }
        stage('Create Internal Kubernetes Infrastructure - Ansible') {
            steps {
                echo 'Create/Comply the Kubernetes internal infrastructre in AWS EC2 using Ansible'
                sh 'ssh-keygen -f "/root/.ssh/known_hosts" -R "ansible"'
                sh 'scp -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa /root/ec2_public_ip jenkins-remote-user@ansible:/home/root/AnsibleSharedFiles/SSHKuberntesInstallation/' 
                //sh 'ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa jenkins-remote-user@ansible "cd /home/root/AnsibleSharedFiles/SSHKuberntesInstallation && ./ansible_deploy.sh $EC2PUBLICIPS"'
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                echo 'service docker start'
            }
        }
        stage('Push') {
            steps {
                echo 'Push image to docker registery...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}