services:
  ansible:
    container_name: ansible
    build:
      context: ./
    volumes:
    # shared folder with my pc
      - "./AnsibleSharedFiles:/home/root/AnsibleSharedFiles/"
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user:
      root
    networks:
      - global-docker-container-network
networks:
  global-docker-container-network:
    external: true
    