services:
  ansible:
    container_name: ansible
    image: ubuntu:20.04
    build:
      context: ./
    volumes:
    # shared folder with my pc
      - "./AnsibleSharedFiles:/home/root/AnsibleSharedFiles/"
    # shared .pem file for connecting to the ec2
      - "../../PrivateFiles/kubernetes-managment-key-pair-private.pem:/home/root/PrivateFiles/kubernetes-managment-key-pair-private.pem"
    
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user:
      root
    networks:
      - global-docker-container-network
networks:
  global-docker-container-network:
    external: true
    