services:
  remote-host-ssh:
    container_name: terraform-aws
    build:
      context: ./
    restart: always
    volumes:
      # Share terraform files with my pc
      - "./TerraformSharedFiles/:/Terraform/TerraformAWSInfrastructure/"
    networks:
      - global-docker-container-network
    privileged: true
    tty: true
    secrets:
      - source: AWSConfig
        target: /root/.aws/config
      - source: AWSCredentials
        target: /root/.aws/credentials
networks:
  global-docker-container-network:
    external: true
# pre configure the awscli
secrets:
  AWSConfig:
    file: /c/Users/almog/Desktop/PrivateFiles/config
  AWSCredentials:
    file: /c/Users/almog/Desktop/PrivateFiles/credentials

# mklink /h "C:\Users\almog\Desktop\DevopsApp\ansible\AnsibleSharedFiles\JenkinsPublicKey\jenkinspublickey.pub" "C:\Users\almog\Desktop\DevopsApp\TerraformAWS\TerraformSharedFiles\JenkinsPublicKey\jenkinspublickey.pub"